### ISSUE TITLE
[CY-2537] Generate and Upload security values to SSM

### ISSUE THREAD

**Issue by rtfpessoa** [codacy/helm-ssm#10]
When retrieving the values from SSM it would be nice to be able to generate and upload security credentials.

This would allow more automated deployments in new environments, with less human intervention.
By storing the keys in SSM the app from then on works and the keys are stored securely.

**Comment by krogebry** [comment]
Would this be like storing the state in SSM?

**Comment by lolgab** [comment]
I'm closing this since we are tracking it internally in Jira.
