### ISSUE TITLE
Specify AWS Profile

### ISSUE THREAD

**Issue by darksinge** [codacy/helm-ssm#19]
I have multiple AWS accounts used for my `dev` and `prod` environments, so
```bash
$ aws ssm get-parameter --name "/my/secret" --query Parameter.Value
```
gives me different output than
```bash
$ aws ssm get-parameter --profile prod --name "/my/secret" --query Parameter.Value
```

Is there a way to achieve a similar thing with this plugin?

**Comment by paulopontesm** [comment]
Hello @darksinge,

You can user environment variables for this.

```bash
$ export AWS_PROFILE=prod
$ aws ssm get-parameter --name "/my/secret" --query Parameter.Value
```

This should have the same result as your second line.

Does this solve your problem?

**Comment by darksinge** [comment]
@paulopontesm Thanks for the reply! I could use that as a workaround, but I think changing `AWS_PROFILE` might just lead to other problems. A lot of tools use that environment variable, and I would prefer not to change it just for this plugin. And I don't trust my memory enough to keep track of the current value of `AWS_PROFILE` after changing it. That is a recipe for accidentally doing something in my production environment when I meant to do it in my dev environment.

Plus, something like this
```bash
$ helm ssm --aws-profile=foo
```
would be so much nicer than
```bash
$ export PREV_AWS_PROFILE=${!AWS_PROFILE}
$ export AWS_PROFILE=foo
$ helm ssm
$ export AWS_PROFILE=${!PREV_AWS_PROFILE}
```

**Comment by paulopontesm** [comment]
`$ AWS_PROFILE=foo helm ssm` also works, so that you don't have to export it.

But if you want to contribute with that flag you are welcome. I see how that can be useful for more people. It would even match how `awscli` does it.

**Comment by paulopontesm** [comment]
@darksinge this was merged. Let us know if it solved your problem.
