### ISSUE TITLE
[CY-2854] add --target-file option to allow output to a different file name

### ISSUE THREAD

**Issue by tugtugtug** [codacy/helm-ssm#27]
**Problem:**
-f option specifies the support of multiple files, thus the -o (target-dir) option makes sense. However, it is also desirable in certain use cases, where the user wants the input files to be processed and saved into a single file with a different file name.
This is essentially what ` -v | tee <file>` does, however there are caveats with piping the output of helm. The most annoying one is that helm prints warnings of various checks into the same stdout/stderr and will pollute the ssm -v output.

**Request:**
add --target-file option to allow output the processed values into a single file.

**Comment by machadoit** [comment]
Hey @tugtugtug we will not prioritise this, but please fell free to add your contribution without changing the default behaviour!
