### ISSUE TITLE
[CY-2991] Set content-type when uploading to Github Assets

### ISSUE THREAD

**Issue by KernCheh** [codacy/helm-ssm#31]
Hi,

Newer versions of helm detects the mime type in the `content-type` header when installing plugins
https://github.com/helm/helm/blob/54ea21d24533d5fc10bc07fe1d4695d8383833a8/pkg/plugin/installer/http_installer.go#L65

Using the instructions to install the latest release:
```
$ helm plugin install https://github.com/codacy/helm-ssm/releases/download/latest/helm-ssm-linux.tgz
```
unfortunately, the mime-type is set to `application/octet-stream` which is not supported in the list. Thus the installer will assume it is a repository installation and results in an error
```
➜  helm plugin install https://github.com/codacy/helm-ssm/releases/download/latest/helm-ssm-linux.tgz
Error: Unable to get repository: Cloning into '/home/user/.cache/helm/plugins/https-github.com-codacy-helm-ssm-releases-download-3.0.1-helm-ssm-linux.tgz'...
remote: Not Found
fatal: repository 'https://github.com/codacy/helm-ssm/releases/download/3.0.1/helm-ssm-linux.tgz/' not found
: exit status 128
```

`ghr` does not seem to pass in the content type properly as well:
https://github.com/tcnksm/ghr/blob/master/github.go#L191

**Comment by KernCheh** [comment]
Currently, I used a workaround which is to download the release file first, and do a local installation.
Alternatively, re-uploading elsewhere with the correct content-type `application/gzip` works as well

**Comment by h314to** [comment]
Thanks for reporting. We'll take a look. The latest official github cli seems to correctly detect the content type, so using it to upload might fix it.

**Comment by paulopontesm** [comment]
It wasn't possible to download from GitHub releases with the correct mime, even after uploading using their new CLI and the right content-type (I confirmed this with their support).

Had change the installation method, but it should be working now:
https://github.com/codacy/helm-ssm#install

**Comment by KernCheh** [comment]
Thank you for the resolution!
