### ISSUE TITLE
[CY-4473] AWS SSO not supported

### ISSUE THREAD

**Issue by macqm** [codacy/helm-ssm#39]
When using AWS with SSO configured, helm ssm fails - not being able to read credentials:

```
template: ssmtpl:24:18: executing "ssmtpl" at <ssm "/myparam">: error calling ssm: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
Error: plugin "ssm" exited with error
```

I believe updating to AWS SDK 1.37+ should help based on this article:
https://aws.amazon.com/blogs/developer/aws-sso-support-in-the-aws-sdk-for-go/

**Comment by machadoit** [comment]
Closing the issue as the PR was already merged.
