### ISSUE TITLE
[CY-4778] Please add ARM binaries

### ISSUE THREAD

**Issue by ivanzolotuhin** [codacy/helm-ssm#42]
Please add binaries for arm. I am unable to install it using `helm plugin add https://github.com/codacy/helm-ssm` command
I am able to compile this by changing
`CGO_ENABLED=0 GOOS=linux GOARCH=amd64   ... ` string by replacing value to `GOARCH=arm64`

**Comment by aquam8** [comment]
I was about the raise the same issue, thank you Ivan for having submitted this. I hope this can come soon as it is also a blocker for us

👍

**Comment by machadoit** [comment]
Hey guys, we will not be doing changes / reviews during August in this repository. Feel free to contribute, wait or fork it.
