### ISSUE TITLE
How to extract values(json format) from parameter store 

### ISSUE THREAD

**Issue by AnubhavSabharwa** [codacy/helm-ssm#43]
We have data available in JSON on parameter store

Example: Parameter: /helm_data/vpc_details
Value: 
{ 
vpc_id: 123456
vpc_cidr_range: 10.0.0.0/16
vpc_private_subnets: 10.0.1.0/24
vpc_public_subnets: 10.0.2.0/24
}
Now, I wanted this to be extracted by helm ssm plugin eg:-

vpc_cidr: {{ ssm /helm_data/vpc_details/vpc_cidr_range region=us-east-1}}

**Comment by h314to** [comment]
You can use [sprig](http://masterminds.github.io/sprig/) functions to further process the output of helm ssm. For instance, for the sample input provided above something like this should work:

```yaml
vpc_cidr: {{ $match:= ssm " /helm_data/vpc_details" "region=us-east-1" | regexFind "vpc_cidr_range.*:.*[0-9./]*" | split ":" }}{{ $match._1 }}
```
