### ISSUE TITLE
[CY-5433] Supporting multiline parameters

### ISSUE THREAD

**Issue by random1st** [codacy/helm-ssm#55]
I want to put a private SSH key into SSM. However I got an error:

 unescaped newline inside substitute pattern

What I can do with?

**Comment by random1st** [comment]
I 'm using workaround: create base64-decoded value and mount it to k8s secret

**Comment by CallMeLeopoldo** [comment]
Secret keys should not be provided as a simple multiline parameter. Coding the value in base64 and providing it as a k8s secret is the way to go.
